spring:
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    topic: "library-events"
    producer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        retries: 11
    admin:
      properties:
        bootstrap-servers: localhost:9092,localhost:9093,localhost:9094

---
spring:
  config:
    activate:
      on-profile: nonprod
  kafka:
    producer:
      bootstrap-servers: nonprod:9095,nonprod:9096,nonprod:9097
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer